name = "s-textpaste"
main = "src/index.ts"
compatibility_date = "2025-06-30"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "s-textpaste-db"
database_id = "a34db08a-94f8-4618-8d7c-ebd93ef6eeb2"

[observability]
enabled = true

[triggers]
crons = ["0 */6 * * *"]
