name = "s-textpaste"
main = "src/index.ts"
compatibility_date = "2026-07-01"

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "s-textpaste-db"
database_id = "6dd2d9bd-9331-49d0-87ac-9c9ab4f4dbd4"

[observability]
enabled = true

[triggers]
crons = ["0 */6 * * *"]
